version: '3.9'
services:
  backend:
    build: backend
    container_name: spring-backend
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 1024M
      restart_policy:
        condition: any

  frontend:
    build:
        context: frontend
        args:
          ENV: prod
    container_name: angular-frontend
    ports:
      - "81:80"
    depends_on:
      - backend
    links:
      - backend:localhost
    deploy:
      restart_policy:
        condition: any
